apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-121
  region: us-east-1

managedNodeGroups:
  - name: managed-ng-public
    minSize: 3
    maxSize: 10
    desiredCapacity: 3
    instanceType: t3.medium
    volumeType: gp3
    volumeSize: 100
    #privateNetworking: true
    # ssh:
    #   allow: true
    #   publicKeyPath: /home/ec2-user/.ssh/authorized_keys
    #   # new feature for restricting SSH access to certain AWS security group IDs
    #   sourceSecurityGroupIds: ["sg-0be6263130f624e61"]
    labels: {
      "role": "worker",
      "network": "public"
    }
    tags:
      nodegroup-role: worker
    subnets:
      - subnet-0c8d3bb9b12b84a8e
      - subnet-044a2f5874efbba13
      - subnet-0bd22b2ebf99f8966
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        autoScaler: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        cloudWatch: true